name = "wutz-dev"
compatibility_date = "2026-06-03"
compatibility_flags = ["nodejs_compat"]
main = "@tanstack/react-start/server-entry"

routes = [
  { pattern = "wutz.dev", custom_domain = true }
]

[observability]
enabled = true
